
name: voc-sqlite
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - lxml>=4.9
  - pillow>=10.0
  - tqdm>=4.66
  - numpy>=1.26
  - pandas>=2.2
  - pip:
      # - opencv-python>=4.9
      # - pyarrow>=15
